Check station permissions in importing app
ImperialCollegeLondon/paricia pull request #230
Opened 2024-03-19 15:13 UTC by tsmbland

2024-03-19 17:42 UTC, tsmbland commented
We can hold off merging this for now in case it breaks something, but does this look reasonable?

2024-03-20 05:39 UTC, dalonsoa requested changes
Just a minor change, but it looks good, otherwise.

2024-03-20 05:39 UTC, dalonsoa commented on importing/views.py
> +            )
This same check should be done above when uploading the temp data (line 58).

2024-03-22 05:35 UTC, dalonsoa approved these changes

2024-03-22 09:29 UTC, merged